// <auto-generated />
namespace QuickProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add7daystoduedate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add7daystoduedate));
        
        string IMigrationMetadata.Id
        {
            get { return "201909200509396_add7daystoduedate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
