// <auto-generated />
namespace QuickProj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_migrationV2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_migrationV2));
        
        string IMigrationMetadata.Id
        {
            get { return "201909190243033_initial_migrationV2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
